services:
  db:
    image: postgres:18
    container_name: greenlight-db
    ports:
      - "127.0.0.1:5432:5432" 
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_DATABASE?Variable not set}
      POSTGRES_PASSWORD: ${DB_PASSWORD?Variable not set}
      POSTGRES_USER: ${DB_USERNAME?Variable not set}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MP_SMTP_AUTH=admin:password123
      - MP_SMTP_AUTH_ALLOW_INSECURE=true

volumes:
  db_data:
